# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180121_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_image_parameter',
            name='image',
            field=models.CharField(max_length=100, verbose_name='图片地址'),
        ),
    ]
