# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180121_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_app_url',
            old_name='download_app_url',
            new_name='download_url',
        ),
    ]
